### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by flashapi** [retyped/ejs-tsd-ambient#1]
Hi,

`var cache: Cache;` is declared twice: at lines 10 and 65.
This wont compile in  typescript 2.1.4.
Could you please remove it from line 65?

Thanks.
